---
- name: Create directory for WWW files
  file:
    path: "{{ www_root }}"
    state: directory
    owner: www-data

- name: Copy nginx config
  template:
    src: templates/nginx.conf.j2
    dest: "{{ nginx_conf_dir }}{{ server_name }}.conf"
  notify:
  - Restart nginx

- name: Copy nginx config for SPARQL endpoint
  template:
    src: templates/nginx.query.conf.j2
    dest: "{{ nginx_conf_dir }}query.{{ server_name }}.conf"
  notify:
  - Restart nginx

- name: Ensure nginx is running
  systemd:
    name: nginx.service
    enabled: yes
    state: started



