---
- name: Install apt packages
  apt:
    name:
      "{{ system_packages }}"
    state: present

- name: Create directory for app
  file:
    path: "{{ install_root }}"
    state: directory

- name: Create directory for www files
  file:
    path: "{{ www_root }}"
    state: directory
    group: www-data

- name: Clone/pull project repo
  git:
    repo: "{{ project_repo }}"
    dest: "{{ install_root }}"

- name: Install python packages
  pip:
    requirements: "{{ install_root }}/requirements.txt"
    virtualenv: "{{ install_root }}/venv"
    virtualenv_command: "{{ python3_executable }} -m venv"

- name: Re-generate feed every 30 minutes
  cron:
    name: "generate feed"
    minute: "*/30"
    job: "{{ generate_feed }}"

- name: Set cron MAILTO
  cron:
    name: MAILTO
    env: yes
    job: "{{ mailto }}"

- name: Copy nginx config
  template:
    src: templates/nginx.conf.j2
    dest: "{{ nginx_conf_dir }}{{ server_name }}.conf"
  notify:
  - Restart nginx

- name: Ensure nginx is running
  systemd:
    name: nginx.service
    enabled: yes
    state: started
