---
- name: Create directory for WWW files
  file:
    path: "{{ www_root }}"
    state: directory
    owner: www-data

- name: Fetch site tarball
  get_url:
    url: "{{ project_repo }}/archive/master.tar.gz"
    dest: /tmp/linkedevents-org.conf

- name: Extract site
  unarchive:
    remote_src: yes
    src: /tmp/linkedevents-org.conf
    dest: "{{ www_root }}"
    extra_opts:
    - --strip-components=1

- name: Remove tarball
  file:
    path: /tmp/linkedevents-org.conf
    state: absent

- name: Symlink to latest versions from root
  file:
    src: "{{ www_root }}/ontology/{{ latest }}/{{ item }}"
    dest: "{{ www_root }}/ontology/{{ item }}"
    owner: www-data
    group: www-data
    state: link
  loop:
     - index.ttl
     - index.rdf
     - index.html

- name: Copy nginx config
  template:
    src: templates/nginx.conf.j2
    dest: "{{ nginx_conf_dir }}{{ server_name }}.conf"
  notify:
  - Restart nginx

- name: Ensure nginx is running
  systemd:
    name: nginx.service
    enabled: yes
    state: started



