---

# Assuming here that we already have a JRE > 11 installed.

# - name: Stop fuseki service
#   systemd:
#     name: fuseki.service
#     state: stopped

- name: Download distribution tarball
  get_url:
    url: "https://dlcdn.apache.org/jena/binaries/apache-jena-fuseki-{{ version }}.tar.gz"
    checksum: "{{ checksum }}"
    dest: "/opt/apache-jena-fuseki-{{ version }}.tar.gz"
    mode: 666

- name: Unarchive tarball
  unarchive:
    src: "/opt/apache-jena-fuseki-{{ version }}.tar.gz"
    dest: /opt
    remote_src: yes

- name: Copy dataset file
  copy:
    src: files/ncg-dataset.ttl
    dest: "/opt/apache-jena-fuseki-{{ version }}/ncg-dataset.ttl"

- name: Add a system user to run under
  user:
    name: fuseki
    comment: Fuseki SPARQL server
    home: "/opt/apache-jena-fuseki-{{ version }}"
    system: yes

- name: Create run directory
  file:
    path: "/opt/apache-jena-fuseki-{{ version }}/run"
    state: directory
    owner: fuseki

- name: Install fuseki service
  template:
    src: templates/fuseki.service.j2
    dest: /etc/systemd/system/fuseki.service
  register: installed_service

- name: Tell systemd to reload configs
  systemd: daemon_reload=yes
  when: installed_service is changed

- name: Start fuseki service
  systemd:
    name: fuseki.service
    enabled: yes
    state: started

- name: Copy nginx config
  template:
    src: templates/nginx.conf.j2
    dest: "{{ nginx_conf_dir }}{{ server_name }}.conf"
  notify:
  - Restart nginx

- name: Ensure nginx is running
  systemd:
    name: nginx.service
    enabled: yes
    state: started
